### ISSUE TITLE
Error "Object does not allow properties to be added or changed."

### ISSUE THREAD

**Issue by kcgthb** [bibliobibulus/cheeriogs#5]
Can't seem to be using cherriogs anymore, as any call to `Cheerio.load()` generates the following error:
```
Object does not allow properties to be added or changed.
```

**Comment by ta2gch** [comment]
I see but I'm going to test it with other google account like your environment. 
Unfortunately I have no time to tackle  to this issue, when I solve that one I tell you again.

However, I suggest you to hard copy to your project, that is not Script ID. You have to copy all script to your project directly. That may solve your issue.

**Comment by ta2gch** [comment]
@kcgthb How about this issue? I think this issue is not caused by my project?

**Comment by zexa** [comment]
Upon following ta2gch advice and uploading the whole script to my own project, executing the following code:
```
function Test() {
  const content = getContent_('https://en.wikipedia.org');
  const $ = Cheerio.load(content);
  Logger.log($('#mp-right').text());
}
```
Returns error
```
[19-04-26 12:07:52:681 EEST] Starting execution
[19-04-26 12:07:52:704 EEST] Execution failed: Invalid property ID. (line 123, file "cheerio_gasify/dom_serializer$gasify") [0 seconds total runtime]
```

**Comment by ta2gch** [comment]
Could you run the following code?

```js
    var content = UrlFetchApp.fetch('https://en.wikipedia.org').getContentText()
    var $ = Cheerio.load(content)
    Logger.log($('#mp-right').text())
```

**Comment by zexa** [comment]
> Could you run the following code?
> 
> ```js
>     var content = UrlFetchApp.fetch('https://en.wikipedia.org').getContentText()
>     var $ = Cheerio.load(content)
>     Logger.log($('#mp-right').text())
> ```

Following code returns 
```
[19-04-26 12:20:24:573 EEST] Starting execution
[19-04-26 12:20:24:699 EEST] UrlFetchApp.fetch([https://en.wikipedia.org]) [0.063 seconds]
[19-04-26 12:20:24:699 EEST] HTTPResponse.getContentText() [0 seconds]
[19-04-26 12:20:24:703 EEST] Execution failed: ReferenceError: "Cheerio" is not defined. (line 3, file "Test") [0.064 seconds total runtime]
```

**Comment by ta2gch** [comment]
@zexa thanks, please add our library `1ReeQ6WO8kKNxoaA_O0XEQ589cIrRvEBA9qcWpNqdOP17i47u6N9M5Xh0` to your project.
This library is defined `Cheerio`

**Comment by bibliobibulus** [comment]
It seems that there are no response for my comment in the future.
