### ISSUE TITLE
errors while loading  library

### ISSUE THREAD

**Issue by jobdiogenes** [bibliobibulus/cheeriogs#8]
I add the project key "1ReeQ6WO8kKNxoaA_O0XEQ589cIrRvEBA9qcWpNqdOP17i47u6N9M5Xh"
to library, select version. 

But library  fail to load.  with many errors like 

<Unknown file>null [1787]
.....
 <Unknown file>__webpadk_required

This can't be use on GAS web editor?

Any ideas?

**Comment by bibliobibulus** [comment]
It is related issue #4 .
